arr = np.array([1, 2, 3])          # 1D Array
arr2d = np.array([[1, 2], [3, 4]]) # 2D Array
zeros = np.zeros((2, 3))           # 2x3 matrix of 0
ones = np.ones((3, 3))             # 3x3 matrix of 1
empty = np.empty((2, 2))           # uninitialized
arange = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)    # equally spaced values
eye = np.eye(3)                    # Identity matrix

### Attributes
arr.shape       # dimensions (rows, cols)
arr.ndim        # number of dimensions
arr.size        # total elements
arr.dtype       # data type
arr.itemsize    # size of each element in bytes
arr.nbytes      # total memory
3. Indexing & Slicing
4. Data Types & Casting
5. Mathematical Operations
  add(a1+a2)
  difference(a1-a2)
  product(a1*a2)
  division(a1/a2)
  modulas(a1%a2)
  power(a**2)

6.Universal Functions (ufuncs)
np.sqrt(a)      # square root
np.exp(a)       # exponential
np.log(a)       # natural log
np.sin(a)       # sine
np.cos(a)       # cosine
np.abs([-1,2])  # absolute


7.aggreagation
a = np.array([[1,2,3],[4,5,6]])
a.sum()        # 21
a.sum(axis=0)  # [5,7,9] column-wise
a.sum(axis=1)  # [6,15] row-wise
a.mean()       # 3.5
a.min()        # 1
a.max()        # 6
a.std()        # standard deviation
a.var()        # variance
np.median(a)   # 3.5
np.percentile(a, 50) # median



## Array Creation

In [5]:
import numpy as np
arr1=[2,3,45,9]
np.array(arr1)

array([ 2,  3, 45,  9])

In [7]:
arr2=[[2,3,1],[9,1,2]]
np.array(arr2).dtype

dtype('int64')

In [9]:
arr2=[[2,3,1],[9,1,2]]
np.array(arr2).ndim

2

In [11]:
arr3=[[[3,4,5],[9,3,4]],[[3,4,6],[8,0,4]]]
np.array(arr3).ndim

3

In [12]:
arr3=[[[3,4,5],[9,3,4]],[[3,4,6],[8,0,4]]]
np.array(arr3).shape

(2, 2, 3)

In [13]:
arr3=[[[3,4,5],[9,3,4]],[[3,4,6],[8,0,4]]]
np.array(arr3).reshape(2,3,2)

array([[[3, 4],
        [5, 9],
        [3, 4]],

       [[3, 4],
        [6, 8],
        [0, 4]]])

In [17]:
arr4=np.array([[[29,10,36,89],[47,38,49,47],[1,2,3,4]],[[36,45,12,14],[12,18,30,48],[45,76,89,79]]])
arr4.ndim

3

In [130]:
arr4.nbytes

64

In [131]:
arr4.dtype

dtype('int64')

In [18]:
arr4.shape

(2, 3, 4)

In [19]:
arr4.size

24

In [27]:
arr4.sum()

np.int64(859)

In [29]:
zero=np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
zero1=np.zeros((4,3,3))
zero1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
zero2=np.zeros((2,2,3,3))
zero2

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [32]:
zero3=np.zeros((2,3,4,2,2))
zero3

array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
  

In [35]:
one1=np.ones((2))
one1

array([1., 1.])

In [36]:
one1.ndim

1

In [37]:
one1.shape

(2,)

In [38]:
one2=np.ones((2,3))
one2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
one3=np.ones((2,3,3))
one3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
empty=np.empty((2))
empty

array([1., 1.])

In [45]:
empty.ndim

1

In [46]:
empty.shape

(2,)

In [47]:
empty2=np.empty((3,3))
empty2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
empty3=np.empty(())
empty3

array(1.24610723e-306)

In [65]:
empty4=np.empty((2,3))
empty4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
arrange1=np.arange(0,10,1)
arrange1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arrange1.ndim

1

In [72]:
arrange2=np.arange(3,15,2)
arrange2

array([ 3,  5,  7,  9, 11, 13])

In [73]:
arange3=np.arange(7)
arange3

array([0, 1, 2, 3, 4, 5, 6])

In [81]:
linspace1=np.linspace(3,5,num=50,endpoint=False)
linspace1

array([3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 ,
       3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72, 3.76, 3.8 , 3.84,
       3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16, 4.2 , 4.24, 4.28,
       4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 , 4.64, 4.68, 4.72,
       4.76, 4.8 , 4.84, 4.88, 4.92, 4.96])

In [82]:
eye=np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Practice

In [83]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [84]:
arr1.ndim

1

In [85]:
arr1.shape

(3,)

In [90]:
arr2=np.array([],dtype=np.int8)
arr2

array([], dtype=int8)

In [93]:
arr3=np.array([2,4,5,6],ndmin=3)
arr3

array([[[2, 4, 5, 6]]])

In [96]:
arr3.ndim

3

In [97]:
arr4=np.array([[2,3,4,5],[29,30,46,48]])
arr4

array([[ 2,  3,  4,  5],
       [29, 30, 46, 48]])

In [98]:
arr4.ndim

2

In [99]:
arr4.shape

(2, 4)

In [100]:
arr4.size

8

In [101]:
np.array(arr4,ndmin=4)

array([[[[ 2,  3,  4,  5],
         [29, 30, 46, 48]]]])

In [102]:
arr4.ndim

2

In [103]:
z1=np.zeros(1)
z1

array([0.])

In [106]:
z2=np.zeros([4])
z2

array([0., 0., 0., 0.])

In [107]:
z2.shape

(4,)

In [108]:
z3=np.zeros([3,4])
z3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
z4=np.zeros((3,2))
z4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [113]:
o1=np.ones(2)
o1

array([1., 1.])

In [116]:
o2=np.ones([2,3])
o2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [118]:
o3=np.ones((4,5))
o3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [119]:
r1=np.arange(0,10)
r1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
r2=np.arange(2,15,2)
r2

array([ 2,  4,  6,  8, 10, 12, 14])

In [126]:
e1=np.empty([])
e1

array(1.e-323)

In [127]:
e2=np.empty([2,3])
e2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [128]:
e3=np.empty([3,3])
e3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [129]:
l1=np.linspace(3,10,num=50)
l1

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [132]:
l1.nbytes

400

In [134]:
l1.dtype

dtype('float64')

In [137]:
l1.itemsize

8

In [138]:
total_memory_size=l1.size*l1.itemsize
total_memory_size

400

## Slicing Or Indexing

In [140]:
import numpy as np
arr1=np.arange(0,10,1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
print(arr1[0])

0


In [143]:
print(arr1[3])

3


In [144]:
print(arr1[1:])

[1 2 3 4 5 6 7 8 9]


In [146]:
print(arr1[:1])

[0]


In [147]:
print(arr1[:3])

[0 1 2]


In [149]:
print(arr1[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [150]:
arr2=np.array([[2,3,4,5],[9,6,7,0]])
arr2

array([[2, 3, 4, 5],
       [9, 6, 7, 0]])

In [151]:
print(arr2[::1])

[[2 3 4 5]
 [9 6 7 0]]


In [152]:
print(arr2[1])

[9 6 7 0]


In [154]:
print(arr2[0])

[2 3 4 5]


In [157]:
print(arr2[2::])

[]


In [159]:
print(arr2[::3])

[[2 3 4 5]]


In [160]:
print(arr2[::4])

[[2 3 4 5]]


In [161]:
print(arr2[1][0])

9


In [162]:
print(arr2[::-1])

[[9 6 7 0]
 [2 3 4 5]]


In [163]:
print(arr2[::-3])

[[9 6 7 0]]


In [164]:
arr2.shape

(2, 4)

In [165]:
arr2.ndim

2

In [173]:
arr3=np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [174]:
arr3.shape

(4,)

In [175]:
arr3.reshape(1,4)

array([[1, 2, 3, 4]])

In [176]:
arr4=np.array([[2,3,4,5],[1,9,7,5],[4,5,0,6]])
arr4

array([[2, 3, 4, 5],
       [1, 9, 7, 5],
       [4, 5, 0, 6]])

In [177]:
arr4[1]

array([1, 9, 7, 5])

In [178]:
arr4[1,2]

np.int64(7)

In [180]:
arr4[2,3]

np.int64(6)

In [181]:
arr4[:,:]

array([[2, 3, 4, 5],
       [1, 9, 7, 5],
       [4, 5, 0, 6]])

In [182]:
arr4[:,3]

array([5, 5, 6])

In [183]:
arr4[2,:]

array([4, 5, 0, 6])

In [184]:
arr4[:,:-1]

array([[2, 3, 4],
       [1, 9, 7],
       [4, 5, 0]])

In [185]:
arr4[:-1,:]

array([[2, 3, 4, 5],
       [1, 9, 7, 5]])

In [187]:
arr4[arr4>3]

array([4, 5, 9, 7, 5, 4, 5, 6])

In [192]:
arr4.flatten()

array([2, 3, 4, 5, 1, 9, 7, 5, 4, 5, 0, 6])

In [193]:
arr5=np.array([2,3,4,5],dtype=np.float32)
arr5

array([2., 3., 4., 5.], dtype=float32)

In [196]:
arr5.astype(int)

array([2, 3, 4, 5])

In [197]:
arr6=np.array([True,False,True,False],dtype=np.bool)
arr6

array([ True, False,  True, False])

In [198]:
arr6.astype(int)

array([1, 0, 1, 0])

In [205]:
arr7=np.array(["a","b","c","d"],dtype=np.bool)
arr7.astype(int)

array([1, 1, 1, 1])

In [210]:
import numpy as np
a1=np.arange(1,5)
a2=np.arange(6,10)

In [211]:
print(a1,a2)

[1 2 3 4] [6 7 8 9]


In [212]:
add=a1+a2
add

array([ 7,  9, 11, 13])

In [213]:
difference=a2-a1
difference

array([5, 5, 5, 5])

In [214]:
product=a1*a2
product

array([ 6, 14, 24, 36])

In [215]:
division=a1/a2
division

array([0.16666667, 0.28571429, 0.375     , 0.44444444])

In [216]:
modulas=a1%a2
modulas

array([1, 2, 3, 4])

In [219]:
arr1=np.array([[2,3,4,5],[9,8,7,6]])
arr2=np.array([[4,3,2,1],[6,7,8,9]])
print(arr1)
print(arr2)

[[2 3 4 5]
 [9 8 7 6]]
[[4 3 2 1]
 [6 7 8 9]]


In [220]:
add=arr1+arr2
add

array([[ 6,  6,  6,  6],
       [15, 15, 15, 15]])

In [221]:
difference=arr1-arr2
difference

array([[-2,  0,  2,  4],
       [ 3,  1, -1, -3]])

In [222]:
product=arr1*arr2
product

array([[ 8,  9,  8,  5],
       [54, 56, 56, 54]])

In [223]:
division=arr1/arr2
division

array([[0.5       , 1.        , 2.        , 5.        ],
       [1.5       , 1.14285714, 0.875     , 0.66666667]])

In [224]:
modulas=arr1%arr2
modulas

array([[2, 0, 0, 0],
       [3, 1, 7, 6]])

## 6.Universal Functions (ufuncs)
np.sqrt(a)      # square root
np.exp(a)       # exponential
np.log(a)       # natural log
np.sin(a)       # sine
np.cos(a)       # cosine
np.abs([-1,2])  # absolute


In [225]:
import pandas as pd
a1=np.arange(10)a
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [239]:
a2=np.array([[1,2,3],[5,6,7]])
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [240]:
sq1=np.square(a2)
sq1

array([[ 1,  4,  9],
       [25, 36, 49]])

In [241]:
sq2=np.square(a2[1])
sq2

array([25, 36, 49])

In [242]:
sq3=np.square(a2[1,1])
sq3

np.int64(36)

In [227]:
sq=np.square(a1)
sq

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [228]:
sqrt=np.sqrt(sq)
sqrt

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [230]:
exp=np.exp(a1)
exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [232]:
log=np.log(a1)
print(log)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\talib\AppData\Local\Temp\ipykernel_26756\3959280260.py:1: RuntimeWarning: divide by zero encountered in log
  log=np.log(a1)


In [235]:
sine=np.sin(a1)
sine

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [237]:
a=60
sina=np.sin(a)
sina

np.float64(-0.3048106211022167)

In [238]:
abs=np.abs(a1)
abs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()        # 21
a.sum(axis=0)  # [5,7,9] column-wise
a.sum(axis=1)  # [6,15] row-wise
a.mean()       # 3.5
a.min()        # 1
a.max()        # 6
a.std()        # standard deviation
a.var()        # variance
np.median(a)   # 3.5
np.percentile(a, 50) # median


In [244]:
import numpy as np
a1=np.array([[11,12,13,14],[15,16,18,19]])
a1

array([[11, 12, 13, 14],
       [15, 16, 18, 19]])

In [246]:
s1=a1.sum()
print(s1)


118


In [247]:
s2=a1.sum(axis=0)
print(s2)

[26 28 31 33]


In [248]:
s3=a1.sum(axis=1)
print(s3)

[50 68]


In [249]:
m1=a1.mean()
print(m1)

14.75


In [251]:
m2=a1.min()
print(m2)

11


In [252]:
m3=a1.max()
print(m3)

19


In [253]:
std=a1.std()
print(std)

2.6339134382131846


In [254]:
var=a1.var()
print(var)

6.9375


In [255]:
median=np.median(a1)
print(median)

14.5


In [257]:
percentile=np.percentile(a1,25)
print(percentile)

12.75


## Practice

In [3]:
import numpy as np
a=np.array([])
print(a)

[]


In [4]:
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

0
(0,)
1
float64


In [5]:
a.astype(int)

array([], dtype=int64)

In [7]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [8]:
print(a1.shape)
print(a1.size)
print(a1.ndim)


(3,)
3
1


In [14]:
print(a1.reshape(3,1))
print(a1.ndim)

[[1]
 [2]
 [3]]
1


In [16]:
a2=np.array([1,2,3],ndmin=2)
print(a2)
print(a2.ndim)

[[1 2 3]]
2


In [18]:
a3=np.array([[2,3,1],[5,4,7]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)

[[2 3 1]
 [5 4 7]]
2
(2, 3)
6
int64


In [21]:
z1=np.zeros([])
print(z1)
print(z1.size)
print(z1.shape)
print(z1.ndim)
print(z1.dtype)

0.0
1
()
0
float64


In [22]:
z2=np.zeros([2])
print(z2)
print(z2.size)
print(z2.shape)
print(z2.ndim)
print(z2.dtype)

[0. 0.]
2
(2,)
1
float64


In [23]:
z3=np.zeros([2,3])
print(z3)
print(z3.size)
print(z3.shape)
print(z3.ndim)
print(z3.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
6
(2, 3)
2
float64


In [28]:
z4=np.zeros([4,3])
print(z4)
print(z4.size)
print(z4.ndim)
print(z4.shape)
print(z4.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
12
2
(4, 3)
float64


In [30]:
o1=np.ones([])
print(o1)
print(o1.shape)
print(o1.size)
print(o1.ndim)
print(o1.dtype)

1.0
()
1
0
float64


In [31]:
o2=np.ones([2])
print(o2)
print(o2.size)
print(o2.shape)
print(o2.ndim)
print(o2.dtype)

[1. 1.]
2
(2,)
1
float64


In [34]:
o3=np.ones([3,2])
print(o3)
print(o3.size)
print(o3.shape)
print(o3.ndim)
print(o3.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
6
(3, 2)
2
float64


In [36]:
e1=np.empty(())
print(e1)
print(e1.size)
print(e1.shape)
print(e1.ndim)
print(e1.dtype)

1.0
1
()
0
float64


In [37]:
e2=np.empty([2])
print(e2)
print(e2.shape)
print(e2.size)
print(e2.ndim)
print(e2.dtype)

[1. 1.]
(2,)
2
1
float64


In [44]:
e3=np.empty([4,3])
print(e3)
print(e3.size)
print(e3.shape)
print(e3.ndim)
print(e3.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
12
(4, 3)
2
float64


In [51]:
eye=np.eye(0)
print(eye)
print(eye.size)
print(eye.shape)
print(eye.ndim)
print(eye.dtype)

[]
0
(0, 0)
2
float64


In [52]:
eye1=np.eye(1,2)
print(eye1)
print(eye1.shape)
print(eye1.size)
print(eye1.ndim)
print(eye1.dtype)

[[1. 0.]]
(1, 2)
2
2
float64


In [53]:
eye2=np.eye(4,3)
print(eye2)
print(eye2.shape)
print(eye2.size)
print(eye2.ndim)
print(eye2.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
(4, 3)
12
2
float64


In [54]:
arr1=np.arange(1,20,3)
print(arr1)

[ 1  4  7 10 13 16 19]


In [57]:
import pandas as pd
arr2=pd.date_range("01-08-2025",periods=10,freq="D")
print(arr2)

DatetimeIndex(['2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11',
               '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15',
               '2025-01-16', '2025-01-17'],
              dtype='datetime64[ns]', freq='D')


In [60]:
arr3=np.arange(10,20,3)
arr3

array([10, 13, 16, 19])

In [61]:
arr4=np.linspace(3,10,num=5,endpoint=True)
arr4

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [62]:
arr5=np.linspace(1,20,num=10,endpoint=True)
arr5

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

## Mathematical operation

In [63]:
import numpy as np
a1=np.arange(5,10,1)
a2=np.arange(10,15,1)
print(a1)
print(a2)

[5 6 7 8 9]
[10 11 12 13 14]


In [64]:
add=a1+a2
add

array([15, 17, 19, 21, 23])

In [65]:
dif=a2-a1
dif

array([5, 5, 5, 5, 5])

In [66]:
product=a1*a2
product

array([ 50,  66,  84, 104, 126])

In [67]:
div=a2/a1
div

array([2.        , 1.83333333, 1.71428571, 1.625     , 1.55555556])

In [68]:
modulas=a1%a2
modulas

array([5, 6, 7, 8, 9])

In [69]:
a3=np.array([[10,20,30],[40,50,60]])
a4=np.array([[100,200,300],[400,500,600]])
print(a3)
print(a4)

[[10 20 30]
 [40 50 60]]
[[100 200 300]
 [400 500 600]]


In [72]:
print(a3)
print(a4)
print("*======"*20)
add=a3+a4
print("ADDITION:")
print(add)
print("*======"*20)
dif=a4-a3
print("DIFFERENCE:")
print(dif)
print("*======"*20)
product=a3*a4
print("PRODUCT:")
print(product)
print("*======"*20)
div=a4/a3
print("DIV:")
print(div)
print("*======"*20)
modulas=a3%a4
print("MODULAS:")
print(modulas)

[[10 20 30]
 [40 50 60]]
[[100 200 300]
 [400 500 600]]
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
ADDITION:
[[110 220 330]
 [440 550 660]]
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
DIFFERENCE:
[[ 90 180 270]
 [360 450 540]]
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
PRODUCT:
[[ 1000  4000  9000]
 [16000 25000 36000]]
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
DIV:
[[10. 10. 10.]
 [10. 10. 10.]]
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
MODULAS:
[[10 20 30]
 [40 50 60]]


In [ ]:
## Aggregate Function
1.arr.sum()
2.arr.min()
3.arr.max()
4.arr.mean()
5.np.meridian()
6.np.var()
7.np.std()

In [75]:
import numpy as np
arr1=np.array([10,12,34])
arr2=np.array([32,31,26])
arr3=np.array([[20,30,45],[10,40,30]])
print(arr1)
print(arr2)
print(arr3)
print("arr1 sum:")
print(arr1.sum())
print("*======"*20)
print("arr2 sum:")
print(arr2.sum())
print("*======"*20)
print("arr3 sum:")
print(arr3.sum())
print("*======"*20)

[10 12 34]
[32 31 26]
[[20 30 45]
 [10 40 30]]
arr1 sum:
56
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
arr2 sum:
89
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
arr3 sum:
175
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======


In [76]:
print("MAX:")
print("arr1 max:")
print(arr1.max())
print("arr2 max:")
print(arr2.max())
print("arr3 max:")
print(arr3.max())
print("*======"*20)

MAX:
arr1 max:
34
arr2 max:
32
arr3 max:
45
*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======


In [77]:
print("MIN:")
print("arr1 min:")
print(arr1.min())
print("arr2 min:")
print(arr2.min())
print("arr3 min:")
print(arr3.min())

MIN:
arr1 min:
10
arr2 min:
26
arr3 min:
10


In [78]:
print("*======"*20)
print("MEAN:")
print("arr1 mean:")
print(arr1.mean())
print("arr2 mean:")
print(arr2.mean())
print("arr3 mean:")
print(arr3.mean())


*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======*======
MEAN:
arr1 mean:
18.666666666666668
arr2 mean:
29.666666666666668
arr3 mean:
29.166666666666668


In [82]:
print("MERIDIAN:")
print("arr1 median:")
m1=np.median(arr1)
print(m1)
print("arr2 median:")
m2=np.median(arr2)
print(m2)
print("arr3 median:")
m3=np.median(arr3)
print(m3)

MERIDIAN:
arr1 median:
12.0
arr2 median:
31.0
arr3 median:
30.0


In [83]:
print("STD:")
print("arr1 std:")
print(arr1.std())
print("arr2 std:")
print(arr2.std())
print("arr3 std:")
print(arr3.std())

STD:
arr1 std:
10.873004286866728
arr2 std:
2.6246692913372702
arr3 std:
11.6963907063485


In [84]:
print("VARIENCE:")
print("arr1 var:")
print(arr1.var())
print("arr2 var:")
print(arr2.var())
print("arr3 var:")
print(arr3.var())

VARIENCE:
arr1 var:
118.22222222222223
arr2 var:
6.888888888888889
arr3 var:
136.80555555555557


In [86]:
print("PERCENTILE:")
print("arr1 percentile:")
p1=np.percentile(arr1,25,keepdims=True)
print(p1)
print("arr2 percentile:")
p2=np.percentile(arr2,75,keepdims=True)
print(p2)
print("arr3 percentile:")
p3=np.percentile(arr3,25,keepdims=True)
print(p3)

PERCENTILE:
arr1 percentile:
[11.]
arr2 percentile:
[31.5]
arr3 percentile:
[[22.5]]


In [ ]:
## universal functions
1.np.square()
2.np.sqrt
3.np.sin()
4.np.cosin()
5.np.log()

In [88]:
import numpy as np
arr1=np.array([2,3,4])
arr2=np.array([[7,8,9],[2,4,6]])
print("Square:")
s=np.square(arr1)
print("square of arr1:")
print(s)
s1=np.square(arr2)
print("square of arr2:")
print(s1)


Square:
square of arr1:
[ 4  9 16]
square of arr2:
[[49 64 81]
 [ 4 16 36]]


In [89]:
print("SQRT:")
sqrt=np.sqrt(s)
print("sqrt of s:")
print(sqrt)
sqrt1=np.sqrt(s1)
print("sqrt of s1:")
print(sqrt1)

SQRT:
sqrt of s:
[2. 3. 4.]
sqrt of s1:
[[7. 8. 9.]
 [2. 4. 6.]]


In [90]:
print("LOG:")
l=np.log(arr1)
print("log of arr1:")
print(l)
l2=np.log(arr2)
print("log of arr2:")
print(l2)

LOG:
log of arr1:
[0.69314718 1.09861229 1.38629436]
log of arr2:
[[1.94591015 2.07944154 2.19722458]
 [0.69314718 1.38629436 1.79175947]]


In [91]:
print("SIN:")
sin1=np.sin(arr1)
print("sin of arr1:")
print(sin1)
sin2=np.sin(arr2)
print("sin of arr2:")
print(sin2)

SIN:
sin of arr1:
[ 0.90929743  0.14112001 -0.7568025 ]
sin of arr2:
[[ 0.6569866   0.98935825  0.41211849]
 [ 0.90929743 -0.7568025  -0.2794155 ]]


In [94]:
print("COS:")
cos1=np.cos(arr1)
print("cos of arr1:")
print(cos1)
cos2=np.cos(arr2)
print("cos of arr2:")
print(cos2)

COS:
cos of arr1:
[-0.41614684 -0.9899925  -0.65364362]
cos of arr2:
[[ 0.75390225 -0.14550003 -0.91113026]
 [-0.41614684 -0.65364362  0.96017029]]


In [95]:
a=1
print(np.sin(a))

0.8414709848078965


In [96]:
print(np.cos(a))

0.5403023058681398


In [97]:
print(np.log(a))

0.0


In [98]:
b=2
print(np.sin(b))
print(np.cos(b))
print(np.log(b))

0.9092974268256817
-0.4161468365471424
0.6931471805599453
