## Advanced function
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.dot(A, B)       # matrix multiplication
A @ B              # same as dot
np.transpose(A)    # transpose
np.linalg.inv(A)   # inverse
np.linalg.det(A)   # determinant
np.linalg.eig(A)   # eigenvalues, eigenvectors
np.linalg.solve(A, np.array([1,2]))  # solve Ax = b
## random function
np.random.rand(3,2)       # uniform [0,1)
np.random.randn(3,2)      # normal distribution
np.random.randint(0,10,5) # 5 integers between 0-9
np.random.choice([1,2,3]) # random element
np.random.seed(42)        # reproducibility
## flatten
a = np.arange(12)       # [0..11]
a.reshape(3,4)          # 3x4 matrix
a.ravel()               # flatten
a.flatten()             # flatten copy
a.T                     # transpose
## sorting and indices
a = np.array([3,1,2])
np.sort(a)         # [1,2,3]
a.argsort()        # [1,2,0] (indices)

b = np.array([[1,4],[3,1]])
np.sort(b, axis=0) # sort column-wise

np.where(a > 1)    # indices where condition true
np.argmax(a)       # index of max
np.argmin(a)       # index of min

## identity
np.identity(3)       # identity matrix
np.diag([1,2,3])     # diagonal matrix
np.tri(3)            # lower triangular



In [1]:
import numpy as np
a=np.array([1,2,3])
a1=np.array([4,5,6])
print(a)
print(a.shape)
print("*=="*5)
print(a1)
print(a1.shape)

[1 2 3]
(3,)
*==*==*==*==*==
[4 5 6]
(3,)


In [2]:
dot=np.dot(a,a1)
print(dot)

32


In [3]:
dot.shape

()

In [6]:
a2=np.array([[2,3,4],[5,6,7]])
a3=np.array([[1,2,3,4],[5,6,7,9],[2,6,8,9]])
print(a2,a2.shape)
print(a3,a3.shape)
dot1=np.dot(a2,a3)
print("*=="*10)
print(dot1,dot1.shape)

[[2 3 4]
 [5 6 7]] (2, 3)
[[1 2 3 4]
 [5 6 7 9]
 [2 6 8 9]] (3, 4)
*==*==*==*==*==*==*==*==*==*==
[[ 25  46  59  71]
 [ 49  88 113 137]] (2, 4)


In [8]:
a4=np.arange(1,10,1)
print(a4,a4.shape)
t=np.transpose(a4)
print("transpose:")
print(t,a4.shape)

[1 2 3 4 5 6 7 8 9] (9,)
transpose:
[1 2 3 4 5 6 7 8 9] (9,)


In [10]:
a5=np.array([[10,11,12,13],[15,16,17,18]])
print(a5,a5.shape)
print("transpose:")
t1=np.transpose(a5)
print(t1,t1.shape)


[[10 11 12 13]
 [15 16 17 18]] (2, 4)
transpose:
[[10 15]
 [11 16]
 [12 17]
 [13 18]] (4, 2)


In [12]:
a6=np.array([[[2,3,4,5],[12,13,14,15],[10,20,30,40]]])
print(a6,a6.shape)
t2=np.transpose(a6)
print("transpose:")
print(t2,t2.shape)

[[[ 2  3  4  5]
  [12 13 14 15]
  [10 20 30 40]]] (1, 3, 4)
transpose:
[[[ 2]
  [12]
  [10]]

 [[ 3]
  [13]
  [20]]

 [[ 4]
  [14]
  [30]]

 [[ 5]
  [15]
  [40]]] (4, 3, 1)


In [35]:
o1=np.ones((1,2,3))
print(o1,o1.shape)
t3=np.transpose(o1,(2,0,1))
print("transpose:")
print(t3,t3.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]] (1, 2, 3)
transpose:
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]] (3, 1, 2)


In [29]:
import numpy as np
a=np.array([[1,2],[1,4]])
print(a,a.shape)
inv=np.linalg.inv(a)
print(inv,inv.shape)

[[1 2]
 [1 4]] (2, 2)
[[ 2.  -1. ]
 [-0.5  0.5]] (2, 2)


In [30]:
a1=np.array([[10,20],[30,40]])
print(a1,a1.shape)
inv1=np.linalg.inv(a1)
print(inv1,inv1.shape)

[[10 20]
 [30 40]] (2, 2)
[[-0.2   0.1 ]
 [ 0.15 -0.05]] (2, 2)


In [32]:
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a2,a2.shape)
inv2=np.linalg.inv(a2)
print(inv2,inv2.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] (1, 3, 3)
[[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
  [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
  [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]] (1, 3, 3)


In [33]:
a3=np.array([[10,15],[20,40]])
print(a3,a3.shape)
d=np.linalg.det(a3)
print("determinant is:")
print(d,d.shape)

[[10 15]
 [20 40]] (2, 2)
determinant is:
99.99999999999996 ()


In [37]:
a4=np.array([[5,10],[15,20]])
print(a4,a4.shape)
eigenvalue,eigenvector=np.linalg.eig(a4)
print("Eigen Values:")
print(eigenvalue)
print("Eigen Vector:")
print(eigenvector)

[[ 5 10]
 [15 20]] (2, 2)
Eigen Values:
[-1.86140662 26.86140662]
Eigen Vector:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [38]:
a5=np.array([[100,200],[300,400]])
print(a5.shape)
inv4=np.linalg.inv(a5)
print("Inverse:")
print(inv4,inv.shape)

(2, 2)
Inverse:
[[-0.02   0.01 ]
 [ 0.015 -0.005]] (2, 2)


In [ ]:
np.random.rand(3,2)       # uniform [0,1)
np.random.randn(3,2)      # normal distribution
np.random.randint(0,10,5) # 5 integers between 0-9
np.random.choice([1,2,3]) # random element
np.random.seed(42)        # reproducibility


In [42]:
import numpy as np
#import random
a=np.random.rand(3,2)
print(a)

[[0.22157132 0.40537603]
 [0.65402535 0.70958948]
 [0.92999793 0.99481592]]


In [45]:
a2=np.random.rand(2)
print(a2)

[0.10318589 0.15488798]


In [46]:
a3=np.random.randn(2,2)
print(a3)

[[ 1.57970403 -1.06194318]
 [-0.25793509  0.11751415]]


In [52]:
a4=np.random.randint(15)
print(a4)

6


In [55]:
a5=np.random.randint(0,10,5)
print(a5)

[3 0 6 5 2]


In [58]:
a6=np.random.randint(1,50,10)
a6

array([12, 13, 29,  9, 22, 10,  3, 40, 25, 33], dtype=int32)

In [59]:
a7=np.random.choice(1,2,4)
a7

array([0, 0], dtype=int32)

In [71]:
a8=np.random.choice([1,2,3])
a8

np.int64(2)

In [80]:
a9=np.arange(20,50,1)
print(a9)
choice=np.random.choice(a9)
print(choice)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
32


In [89]:
a10=np.random.randint(100,200,10)
print(a10)
choice_1=np.random.choice(a10)
print(choice_1)

[168 187 142 161 188 137 155 157 164 119]
168


In [99]:
linspace=np.linspace(2,4,10)
print(linspace)

[2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
 3.33333333 3.55555556 3.77777778 4.        ]


In [100]:
a11=np.random.rand(1,3,2,3)
print(a11)

[[[[0.94408529 0.5843537  0.07891271]
   [0.18416522 0.25623646 0.23948753]]

  [[0.32101304 0.98281972 0.49502722]
   [0.08368569 0.75845426 0.59719232]]

  [[0.18354582 0.33064416 0.51467874]
   [0.43078693 0.09727102 0.63875671]]]]


In [105]:
a11=np.random.randint(10,100,20)
print("Random Number:")
print(a11)
choice_3=np.random.choice(a11)
print("Random Choice is :")
print(choice_3)

Random Number:
[63 81 46 23 22 31 98 47 91 76 74 65 41 43 16 15 17 92 99 32]
Random Choice is :
15


In [ ]:
a = np.arange(12)       # [0..11]
a.reshape(3,4)          # 3x4 matrix
a.ravel()               # flatten
a.flatten()             # flatten copy
a.T                     # transpose


In [112]:
import numpy as np
a=np.arange(5)
print(a,a.shape)

[0 1 2 3 4] (5,)


In [113]:
a.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [114]:
a.ravel()

array([0, 1, 2, 3, 4])

In [115]:
a1=np.array([[2,3,4],[5,6,7]])
a1.reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [120]:
a1.reshape(2,3)

array([[2, 3, 4],
       [5, 6, 7]])

In [122]:
flat=a1.ravel()
flat

array([2, 3, 4, 5, 6, 7])

In [123]:
flat1=a1.flatten()
flat1

array([2, 3, 4, 5, 6, 7])

In [124]:
a1

array([[2, 3, 4],
       [5, 6, 7]])

In [125]:
transpose=a1.T
transpose

array([[2, 5],
       [3, 6],
       [4, 7]])

In [126]:
t2=np.transpose(a1)
t2

array([[2, 5],
       [3, 6],
       [4, 7]])

In [ ]:
a = np.array([3,1,2])
np.sort(a)         # [1,2,3]
a.argsort()        # [1,2,0] (indices)

b = np.array([[1,4],[3,1]])
np.sort(b, axis=0) # sort column-wise

np.where(a > 1)    # indices where condition true
np.argmax(a)       # index of max
np.argmin(a)       # index of min


In [129]:
import numpy as np
a=np.random.randint(10,20,10)
s=np.sort(a)
print(s)

[10 12 13 13 14 16 16 16 16 19]


In [130]:
index=np.argsort(a)
print(index)

[7 1 6 2 5 0 4 8 9 3]


In [131]:
np.argmax(a)

np.int64(3)

In [132]:
np.argmin(a)

np.int64(7)

In [133]:
np.where(a>1)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [134]:
a2=np.array([[7,3,8,9,-10,-3],[20,-4,9,21,29,-3]])
print(a2)

[[  7   3   8   9 -10  -3]
 [ 20  -4   9  21  29  -3]]


In [135]:
s2=np.sort(a2)
s2

array([[-10,  -3,   3,   7,   8,   9],
       [ -4,  -3,   9,  20,  21,  29]])

In [136]:
s3=np.sort(a2,axis=1)
s3

array([[-10,  -3,   3,   7,   8,   9],
       [ -4,  -3,   9,  20,  21,  29]])

In [137]:
s4=np.sort(a2,axis=0)
s4

array([[  7,  -4,   8,   9, -10,  -3],
       [ 20,   3,   9,  21,  29,  -3]])

In [138]:
arg=np.argsort(a2)
arg

array([[4, 5, 1, 0, 2, 3],
       [1, 5, 2, 0, 3, 4]])

In [140]:
arg1=a2.argmax()
print(arg1)

10


In [141]:
arg2=a2.argmin()
arg2

np.int64(4)

In [ ]:
np.identity(3)       # identity matrix
np.diag([1,2,3])     # diagonal matrix
np.tri(3)            # lower triangular


In [157]:
import numpy as np
a=np.identity(2,2)
print(a)

TypeError: Cannot interpret '2' as a data type

In [152]:
a1=np.identity(4)
a1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [156]:
b=np.eye(3,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [160]:
c=np.diag([3,2,3])
print(c)

[[3 0 0]
 [0 2 0]
 [0 0 3]]


In [168]:
t=np.tri(3,2,4)
t

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [169]:
t1=np.tri(2,2)
t1

array([[1., 0.],
       [1., 1.]])