In [1]:
import numpy as np
a=np.array()
print(a)

TypeError: array() missing required argument 'object' (pos 0)

In [4]:
a1=np.array([])
print(a1)
print("shape:\n",a1.shape)
print("size:\n",a1.size)
print("ndim:\n",a1.ndim)
print("dtype:\n",a1.dtype)
print("itemsize:\n",a1.itemsize)
print("nbytes:\n",a1.nbytes)
print("memory used:\n",a1.itemsize*a1.nbytes)

[]
shape:
 (0,)
size:
 0
ndim:
 1
dtype:
 float64
itemsize:
 8
nbytes:
 0
memory used:
 0


In [5]:
a2=np.array([[2,1,2,3,],[3,4,5,2]])
print(a2)
print("Shape:\n",a2.shape)
print("size:\n",a2.size)
print("ndim:\n",a2.ndim)
print("dtype:\n",a2.dtype)
print("itemsize:\n",a2.itemsize)
print("nbytes:\n",a2.nbytes)
print("memory used:\n",a2.itemsize*a2.nbytes)

[[2 1 2 3]
 [3 4 5 2]]
Shape:
 (2, 4)
size:
 8
ndim:
 2
dtype:
 int64
itemsize:
 8
nbytes:
 64
memory used:
 512


In [6]:
a3=np.arange()
print(a3)

TypeError: arange() requires stop to be specified.

In [8]:
a4=np.arange(5,15,2)
print(a4)
print("shape:\n",a4.shape)
print("size:\n",a4.size)
print("ndim:\n",a4.ndim)
print("dtype:",a4.dtype)
print("itemsize:\n",a4.itemsize)
print("nbytes:\n",a4.nbytes)
print("memory used:\n",a4.itemsize*a4.nbytes)

[ 5  7  9 11 13]
shape:
 (5,)
size:
 5
ndim:
 1
dtype: int64
itemsize:
 8
nbytes:
 40
memory used:
 320


In [12]:
z=np.zeros()
print(z)

TypeError: zeros() missing required argument 'shape' (pos 0)

In [13]:
z1=np.zeros([])
print(z1)
print("shape:\n",z1.shape)
print("size:\n",z1.size)
print("ndim:\n",z1.ndim)
print("dtype:\n",z1.dtype)
print("itemsize:\n",z1.itemsize)
print("nbytes:\n",z1.nbytes)
print("memory used:\n",z1.itemsize*z1.nbytes)

0.0
shape:
 ()
size:
 1
ndim:
 0
dtype:
 float64
itemsize:
 8
nbytes:
 8
memory used:
 64


In [11]:
z2=np.zeros([2,3])
print(z2)
print("shape:\n",z2.shape)
print("size:\n",z2.size)
print("ndim:\n",z2.ndim)
print("dtype:\n",z2.dtype)
print("itemsize:\n",z2.itemsize)
print("nbytes:",z2.nbytes)
print("memory used:\n",z2.itemsize*z2.nbytes)

[[0. 0. 0.]
 [0. 0. 0.]]
shape:
 (2, 3)
size:
 6
ndim:
 2
dtype:
 float64
itemsize:
 8
nbytes: 48
memory used:
 384


In [14]:
o=np.ones()
print(o)

TypeError: ones() missing 1 required positional argument: 'shape'

In [15]:
o1=np.ones([])
print(o1)
print("shape:",o1.shape)
print("size:",o1.size)
print("ndim:",o1.ndim)
print("dtype:",o1.dtype)
print("itemsiz:",o1.itemsize)
print("nbytes:",o1.nbytes)
print("memory used:",o1.itemsize*o1.nbytes)

1.0
shape: ()
size: 1
ndim: 0
dtype: float64
itemsiz: 8
nbytes: 8
memory used: 64


In [17]:
o2=np.ones([2,2])
print(o2)
print("shape:",o2.shape)
print("size:",o2.size)
print("ndim:",o2.ndim)
print("dtype:",o2.dtype)
print("itemsize:",o2.itemsize)
print("nbytes:",o2.nbytes)
print("memory used:",o2.itemsize*o2.nbytes)

[[1. 1.]
 [1. 1.]]
shape: (2, 2)
size: 4
ndim: 2
dtype: float64
itemsize: 8
nbytes: 32
memory used: 256


In [18]:
e=np.empty()
print(e)

TypeError: empty() missing required argument 'shape' (pos 0)

In [19]:
e1=np.empty([])
print(e1)
print("shape:",e1.shape)
print("size:",e1.size)
print("ndim:",e1.ndim)
print("dtype:",e1.dtype)
print("itemsize:",e1.itemsize)
print("nbytes:",e1.nbytes)
print("memory used:",e1.itemsize*e1.nbytes)

1.0
shape: ()
size: 1
ndim: 0
dtype: float64
itemsize: 8
nbytes: 8
memory used: 64


In [25]:
e2=np.empty([2,2])
print(e2)
print("shape:",e2.shape)
print("size:",e2.size)
print("ndim:",e2.ndim)
print("dtype:",e2.dtype)
print("itemsize:",e2.itemsize)
print("nbytes:",e2.nbytes)
print("memory used:",e2.itemsize*e2.nbytes)

[[1. 1.]
 [1. 1.]]
shape: (2, 2)
size: 4
ndim: 2
dtype: float64
itemsize: 8
nbytes: 32
memory used: 256


In [26]:
l=np.linspace()
print(l)

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [32]:
l1=np.linspace(5,10)
print(l1)
print("shape:",l1.shape)
print("size:",l1.size)
print("ndim:",l1.ndim)
print("dtype:",l1.dtype)
print("itemsize:",l1.itemsize)
print("nbytes:",l1.nbytes)
print("memory used:",l1.itemsize*l1.nbytes)

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]
shape: (50,)
size: 50
ndim: 1
dtype: float64
itemsize: 8
nbytes: 400
memory used: 3200


In [36]:
l2=np.linspace([2,5,2],[3,8,4])
print(l2)
print("shape:",l2.shape)
print("size:",l2.size)
print("ndim:",l2.ndim)
print("dtype:",l2.dtype)
print("itemsize:",l2.itemsize)
print("nbytes:",l2.nbytes)
print("memory used:",l2.itemsize)

[[2.         5.         2.        ]
 [2.02040816 5.06122449 2.04081633]
 [2.04081633 5.12244898 2.08163265]
 [2.06122449 5.18367347 2.12244898]
 [2.08163265 5.24489796 2.16326531]
 [2.10204082 5.30612245 2.20408163]
 [2.12244898 5.36734694 2.24489796]
 [2.14285714 5.42857143 2.28571429]
 [2.16326531 5.48979592 2.32653061]
 [2.18367347 5.55102041 2.36734694]
 [2.20408163 5.6122449  2.40816327]
 [2.2244898  5.67346939 2.44897959]
 [2.24489796 5.73469388 2.48979592]
 [2.26530612 5.79591837 2.53061224]
 [2.28571429 5.85714286 2.57142857]
 [2.30612245 5.91836735 2.6122449 ]
 [2.32653061 5.97959184 2.65306122]
 [2.34693878 6.04081633 2.69387755]
 [2.36734694 6.10204082 2.73469388]
 [2.3877551  6.16326531 2.7755102 ]
 [2.40816327 6.2244898  2.81632653]
 [2.42857143 6.28571429 2.85714286]
 [2.44897959 6.34693878 2.89795918]
 [2.46938776 6.40816327 2.93877551]
 [2.48979592 6.46938776 2.97959184]
 [2.51020408 6.53061224 3.02040816]
 [2.53061224 6.59183673 3.06122449]
 [2.55102041 6.65306122 3.10

In [39]:
import numpy as np
a=np.array([])
print("sum:",a.sum())
#print("min:",a.min()) Error pron
#print("max:",a.max())
print("mean:",a.mean())
print("var:",a.var())
print("std:",a.std())
print("square:",np.square(a))
print("sqrt:",np.sqrt(a))
print("log:",np.log(a))
print("sin:",np.sin(a))
print("cos:",np.cos(a))
print("exp:",np.exp(a))
print("median:",np.median(a))
#print("percentile:",np.percentile(a,75))

sum: 0.0
mean: nan
var: nan
std: nan
square: []
sqrt: []
log: []
sin: []
cos: []
exp: []
median: nan


C:\Users\talib\AppData\Local\Temp\ipykernel_11308\3120725010.py:6: RuntimeWarning: Mean of empty slice.
  print("mean:",a.mean())
C:\Users\talib\AppData\Local\Temp\ipykernel_11308\3120725010.py:7: RuntimeWarning: Degrees of freedom <= 0 for slice
  print("var:",a.var())


In [41]:
a1=np.array([2,3,4])
print(a1)
print("sum:",a1.sum())
print("min:",a1.min())
print("max:",a1.max())
print("mean:",a1.mean())
print("std:",a1.std())
print("var:",a1.var())
print("median:",np.median(a1))
print("percentile:",np.percentile(a1,75))
print("square:",np.square(a1))
print("sqrt:",np.sqrt(a1))
print("log:",np.log(a1))
print("sin:",np.sin(a1))
print("cos:",np.cos(a1))
print("ex:",np.exp(a1))

[2 3 4]
sum: 9
min: 2
max: 4
mean: 3.0
std: 0.816496580927726
var: 0.6666666666666666
median: 3.0
percentile: 3.5
square: [ 4  9 16]
sqrt: [1.41421356 1.73205081 2.        ]
log: [0.69314718 1.09861229 1.38629436]
sin: [ 0.90929743  0.14112001 -0.7568025 ]
cos: [-0.41614684 -0.9899925  -0.65364362]
ex: [ 7.3890561  20.08553692 54.59815003]


In [44]:
a2=np.array([[10,20,30],[5,10,15]])
print("array:",a2)
print(f"sum:{a2.sum()} ,shape:{a2.sum().shape},ndim:{a2.sum().ndim},dtype:{a2.sum().dtype}")
print(f"min:{a2.min()},shape:{a2.min().shape},ndim:{a2.min().ndim},dtype:{a2.min().dtype}")
print(f"max:{a2.max()},shape:{a2.max().shape},ndim:{a2.max().ndim},dtype:{a2.max().dtype}")
print(f"mean:{a2.mean()},shape:{a2.mean().shape},ndim:{a2.mean().ndim},dtype:{a2.mean().dtype}")
print(f"var:{a2.var()},shape:{a2.var().shape},ndim:{a2.var().ndim},dtype:{a2.var().dtype}")
print(f"std:{a2.std()},shape:{a2.std().shape},ndim:{a2.std().ndim},dtype:{a2.std().dtype}")
print(f"median:{np.median(a2)},shape:{np.median(a2).shape},ndim:{np.median(a2).ndim},dtype:{np.median(a2).dtype}")
print(f"percentile:{np.percentile(a2,75)},shape:{np.percentile(a2,75).shape},ndim:{np.percentile(a2,75).ndim},dtype:{np.percentile(a2,75).dtype}")
print(f"square:{np.square(a2)},shape:{np.square(a2).shape},ndim:{np.square(a2).ndim},dtype:{np.square(a2).dtype}")
print(f"sqrt:{np.sqrt(a2)},shape:{np.sqrt(a2).shape},ndim:{np.sqrt(a2).ndim},dtype:{np.sqrt(a2).dtype}")
print(f"log:{np.log(a2)},shape:{np.log(a2).shape},ndim:{np.log(a2).ndim},dtype:{np.log(a2).dtype}")
print(f"sin:{np.sin(a2)},shape:{np.sin(a2).shape},ndim:{np.sin(a2).ndim},dtype:{np.sin(a2).dtype}")
print(f"cos:{np.cos(a2)},shape:{np.cos(a2).shape},ndim:{np.cos(a2).ndim},dtype:{np.cos(a2).dtype}")
print(f"exp:{np.exp(a2)},shape:{np.exp(a2).shape},ndim:{np.exp(a2).ndim},dtype:{np.exp(a2).dtype}")

array: [[10 20 30]
 [ 5 10 15]]
sum:90 ,shape:(),ndim:0,dtype:int64
min:5,shape:(),ndim:0,dtype:int64
max:30,shape:(),ndim:0,dtype:int64
mean:15.0,shape:(),ndim:0,dtype:float64
var:66.66666666666667,shape:(),ndim:0,dtype:float64
std:8.16496580927726,shape:(),ndim:0,dtype:float64
median:12.5,shape:(),ndim:0,dtype:float64
percentile:18.75,shape:(),ndim:0,dtype:float64
square:[[100 400 900]
 [ 25 100 225]],shape:(2, 3),ndim:2,dtype:int64
sqrt:[[3.16227766 4.47213595 5.47722558]
 [2.23606798 3.16227766 3.87298335]],shape:(2, 3),ndim:2,dtype:float64
log:[[2.30258509 2.99573227 3.40119738]
 [1.60943791 2.30258509 2.7080502 ]],shape:(2, 3),ndim:2,dtype:float64
sin:[[-0.54402111  0.91294525 -0.98803162]
 [-0.95892427 -0.54402111  0.65028784]],shape:(2, 3),ndim:2,dtype:float64
cos:[[-0.83907153  0.40808206  0.15425145]
 [ 0.28366219 -0.83907153 -0.75968791]],shape:(2, 3),ndim:2,dtype:float64
exp:[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [1.48413159e+02 2.20264658e+04 3.26901737e+06]],sha

In [45]:
import numpy as np
d=np.diag()
print(d)

TypeError: diag() missing 1 required positional argument: 'v'

In [49]:
d1=np.diag([])
print(d1)
print("shape:",d1.shape)
print("size:",d1.size)
print("ndim:",d1.ndim)
print("dtype:",d1.dtype)
print("itemsize:",d1.itemsize)
print("nbytes:",d1.nbytes)
print("memory used:",d1.itemsize*d1.nbytes)

[]
shape: (0, 0)
size: 0
ndim: 2
dtype: float64
itemsize: 8
nbytes: 0
memory used: 0


In [51]:
d2=np.diag([3,3,4,5,6])
print(d2)
print("shape:",d2.shape)
print("size:",d2.size)
print("ndim:",d2.ndim)
print("dtype:",d2.dtype)
print("itemsize:",d2.itemsize)
print("nbytes:",d2.nbytes)
print("memory used:",d2.itemsize*d2.nbytes)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]
shape: (5, 5)
size: 25
ndim: 2
dtype: int64
itemsize: 8
nbytes: 200
memory used: 1600


In [52]:
t=np.tri()
print(t)

TypeError: tri() missing 1 required positional argument: 'N'

In [59]:
t1=np.tri(4,5)
print(t1)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]]


In [60]:
i=np.identity()
print(i)

TypeError: identity() missing 1 required positional argument: 'n'

In [72]:
i1=np.identity(5)
print(i1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [73]:
e=np.eye()
print(e)

TypeError: eye() missing 1 required positional argument: 'N'

In [84]:
e1=np.eye(7,3,2)
print(e1)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
import numpy as np
a=np.array([[5,10],[20,25]])
b=np.array([[2,3,4],[5,7,9]])
print("\ndot product:\n",np.dot(a,b))
inv=np.linalg.inv(a)
print("\nInverse of a matrix:\n",inv)
det=np.linalg.det(a)
print("\nDeterminant:\n",det)
eigenvalue , eigenvector=np.linalg.eig(a)
print("\nEigenvalue:\n",eigenvalue)
print("\nEigenvector:\n",eigenvector)


dot product:
 [[ 60  85 110]
 [165 235 305]]

Inverse of a matrix:
 [[-0.33333333  0.13333333]
 [ 0.26666667 -0.06666667]]

Determinant:
 -74.99999999999997

Eigenvalue:
 [-2.32050808 32.32050808]

Eigenvector:
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [90]:
print("Before transpose:\n",b)
print("shape:",b.shape)
b1=np.transpose(b)
print("After transpose:\n",b1)
print("shape:",b1.shape)


Before transpose:
 [[2 3 4]
 [5 7 9]]
shape: (2, 3)
After transpose:
 [[2 5]
 [3 7]
 [4 9]]
shape: (3, 2)


In [91]:
print("reshape b1:",b1.reshape(2,3))

reshape b1: [[2 5 3]
 [7 4 9]]


In [93]:
b1.flatten()

array([2, 5, 3, 7, 4, 9])

In [94]:
a.ravel()

array([ 5, 10, 20, 25])

In [108]:
import numpy as np
a=np.random.rand(3,5,4)*10
print(a)

[[[1.18151292 8.90751733 7.5157242  4.39864133]
  [5.61893901 0.17216633 0.91461126 9.3060025 ]
  [1.69500683 6.96396288 4.27672623 2.36958245]
  [3.87700262 9.56955714 1.48445625 5.10452059]
  [8.11408608 3.72529284 0.97628527 3.0776557 ]]

 [[8.22452403 2.90963899 9.61835738 5.90677866]
  [3.73701598 8.84888336 2.43691984 2.06687676]
  [6.55193624 9.44013612 7.34413562 3.52413339]
  [4.02039088 2.90003593 9.40071657 0.1874479 ]
  [7.84735255 9.83918171 9.11817182 9.96812696]]

 [[9.62102697 9.95195742 8.03629191 9.91447882]
  [1.01176752 3.16678676 9.09790814 3.91269765]
  [5.43664172 3.8111592  7.14787187 3.17728901]
  [2.61644987 8.39327319 4.80933702 5.19457905]
  [5.99297024 9.10495676 9.08705341 2.31995866]]]


In [107]:
a1=np.random.randn(2,3,4)*10
print(a1)

[[[ -3.97191938   3.03480064  -7.32822898 -16.15598403]
  [-16.57209472  -0.69638624   0.36801175  13.45678831]
  [  2.77207051  12.90917806  -9.07891821  10.31698112]]

 [[ -3.32362968 -10.7915889   -8.92947461  11.85869078]
  [ 17.29422022  15.26842618   0.3076804   11.53161685]
  [  4.27965147 -19.23557213   6.76521945  27.31093872]]]


In [109]:
a2=np.random.randint(5,10,15)
print(a2)

[9 6 8 7 8 6 7 7 6 5 9 5 9 8 8]


In [115]:
a3=np.random.choice(a2)
a3

np.int32(7)