In [ ]:
# PROBLEM.1
Task 1.1: Create a 1-D NumPy array named daily_revenue_lakhs from the provided list. The values are in Lakhs INR.
Task 1.2: Calculate and print the total revenue for the two weeks.
Task 1.3: Calculate and print the average daily revenu

In [2]:
import numpy as np
daily_revenue_data = [
5.5, 6.2, 5.8, 7.1, 7.5, 8.0, 9.2,
6.0, 6.5, 7.0, 7.8, 8.5, 9.0, 9.5]
# List to Numpy Array Conversion
daily_revenue_lakhs=np.array(daily_revenue_data)

In [5]:
# Total Revenue Calculation
total_revenue=daily_revenue_lakhs.sum()
print(f"Total Revenue:{total_revenue}")

Total Revenue:103.6


In [6]:
# Average daily revenue Calculation
avg_daily_revenue=daily_revenue_lakhs.mean()
print("Average Daily Revenue :",avg_daily_revenue)

Average Daily Revenue : 7.3999999999999995


In [ ]:
# PROBLEM.2
Task 2.1: Create a 2-D NumPy array named product_sales from the nested list. The first row represents units sold, and
the second row represents cost per unit. The columns correspond to 'Cups', 'Cones', and 'Specials'.
Task 2.2: Use array indexing to print the total number of 'Cones' sold.
Task 2.3: Use array slicing to print the costs for 'Cones' and 'Specials'.

In [7]:
import numpy as np
product_sales_data = [
[1500, 2200, 800], # Units sold for Cups, Cones, Specials
[30, 20, 150]  # Cost per unit (in INR) for Cups, Cones, Specials
]
# List to Numpy Array Conversion
product_sales=np.array(product_sales_data)
print(product_sales)

[[1500 2200  800]
 [  30   20  150]]


In [8]:
# Indexing For Cones
total_number_cones=product_sales[0][1]
print(total_number_cones)

2200


In [11]:
# Costs for Cones & Specials
cone,specials=product_sales[1][1:3]
print("Cost:")
print(f"Cone Price:{cone}, Special Price:{specials}")

Cost:
Cone Price:20, Special Price:150


In [ ]:
# PROBLEM.3
Task 3.1: Create a 1-D NumPy array named unit_costs with the provided data.
Task 3.2: Define a variable profit_margin_percent with a value of 25.
Task 3.3: Calculate the selling price for each unit by adding the profit margin. The formula is: selling_price =
unit_cost + (unit_cost * profit_margin_percent / 100). Store the result in a new array named selling_prices.

In [12]:
import numpy as np
unit_costs_data = [45, 60, 55, 70, 80] # In INR
# List to Numpy Array Conversion
unit_costs=np.array(unit_costs_data)
print(unit_costs)


[45 60 55 70 80]


In [13]:
# Calculating Selling Price for each element
profit_margin_percent=25
selling_prices =unit_costs + (unit_costs * profit_margin_percent / 100)
print("Selling Prices Array:")
print(selling_prices)

Selling Prices Array:
[ 56.25  75.    68.75  87.5  100.  ]


In [ ]:
# PROBLEM.4
Task 4.1: Create a 2-D NumPy array named ingredients_used. The rows represent three flavors and the columns
represent three ingredients (e.g., 'Vanilla', 'Chocolate', 'Fruits').
Task 4.2: Create a 1-D NumPy array named batches_produced representing the number of batches for each flavor.
Task 4.3: Use NumPy broadcasting to calculate the total amount of each ingredient used across all batches. Print the result

In [16]:
import numpy as np
# Given data
# rows: Flavors (A, B, C)
# cols: Ingredients (Vanilla, Chocolate, Fruit)
ingredients_used_per_batch = [
[0.5, 0.3, 0.1],
[0.2, 0.6, 0.0],
[0.4, 0.2, 0.3]
]
batches_produced_data = [100, 150, 200]
# 2D Array Creation
ingredients_used=np.array(ingredients_used_per_batch)
print(f"Ingredients Used :{ingredients_used}")
batches_produced=np.array(batches_produced_data)
print(f"Batches Produced:{batches_produced}")

Ingredients Used :[[0.5 0.3 0.1]
 [0.2 0.6 0. ]
 [0.4 0.2 0.3]]
Batches Produced:[100 150 200]


In [21]:
amount_1=ingredients_used*batches_produced
total_amount_ingredients=amount_1.sum(axis=0)
print("Total Amount:",total_amount_ingredients)

Total Amount: [110. 165.  80.]


In [24]:
# Each Product's Total Amount
vanilla,chocolate,fruit=total_amount_ingredients
print("Total Amount:")
print("Vanilla Price:",vanilla)
print("Chocolate Price:",chocolate)
print("Fruit Price:",fruit)


Total Amount:
Vanilla Price: 110.0
Chocolate Price: 165.0
Fruit Price: 80.0
