In [5]:
import numpy as np
a=np.array()
print(a)
print("*===*"*10)
a1=np.array([])
print(a1,a1.shape,a1.size,a1.ndim,a1.dtype,a1.itemsize,a1.nbytes)

*===**===**===**===**===**===**===**===**===**===*
[] (0,) 0 1 float64 8 0


In [6]:
print("*===*"*10)
a1=np.array([])
print(a1,a1.shape,a1.size,a1.ndim,a1.dtype,a1.itemsize,a1.nbytes)

*===**===**===**===**===**===**===**===**===**===*
[] (0,) 0 1 float64 8 0


In [7]:
a2=np.array([2,3,4])
print(a2.shape)
print("size:",a2.size)
print("ndim:",a2.ndim)
print("shape:",a2.shape)
print("dtype:",a2.dtype)
print("itemsize:",a2.itemsize)
print("nbytes:",a2.nbytes)
print("a2.memory used:",a2.itemsize*a2.nbytes)

(3,)
size: 3
ndim: 1
shape: (3,)
dtype: int64
itemsize: 8
nbytes: 24
a2.memory used: 192


In [8]:
a3=np.array([[1,2,3,4],[2,3,4,5]])
print(a3)
print("size:",a3.size)
print("shape:",a3.shape)
print("ndim:",a3.ndim)
print("dtype:",a3.dtype)
print("itemsize:",a3.itemsize)
print("nbytes:",a3.nbytes)
print("memory used:",a3.itemsize*a3.nbytes)

[[1 2 3 4]
 [2 3 4 5]]
size: 8
shape: (2, 4)
ndim: 2
dtype: int64
itemsize: 8
nbytes: 64
memory used: 512


In [9]:
a4=np.arange(1,10,2)
print(a4)
print("size:",a4.size)
print("shape:",a4.shape)
print("ndim:",a4.ndim)
print("itemsize:",a4.itemsize)
print("nbytes:",a4.nbytes)
print("memory used:",a4.itemsize*a4.nbytes)

[1 3 5 7 9]
size: 5
shape: (5,)
ndim: 1
itemsize: 8
nbytes: 40
memory used: 320


In [10]:
z=np.zeros()
print(z)

TypeError: zeros() missing required argument 'shape' (pos 0)

In [12]:
z1=np.zeros([])
print(z1)
print("size:",z1.size)
print("shape:",z1.shape)
print("ndim:",z1.ndim)
print("itemsize:",z1.itemsize)
print("nbytes:",z1.nbytes)
print("memory used:",z1.itemsize*z1.nbytes)

0.0
size: 1
shape: ()
ndim: 0
itemsize: 8
nbytes: 8
memory used: 64


In [17]:
z2=np.zeros([1,2,6])
print(z2)
print("size:",z2.size)
print("shape:",z2.shape)
print("ndim:",z2.ndim)
print("itemsize:",z2.itemsize)
print("dtype:",z2.dtype)
print("nbytes:",z2.nbytes)
print("memory used:",z2.itemsize*z2.nbytes)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
size: 12
shape: (1, 2, 6)
ndim: 3
itemsize: 8
dtype: float64
nbytes: 96
memory used: 768


In [18]:
o=np.ones()
print(0)

TypeError: ones() missing 1 required positional argument: 'shape'

In [20]:
o1=np.ones([])
print(o1)
print("size:",o1.size)
print("shape:",o1.shape)
print("ndim:",o1.ndim)
print("dtype:",o1.dtype)
print("itemsize:",o1.itemsize)
print("nbytes:",o1.nbytes)
print("memory used:",o1.itemsize*o1.nbytes)

1.0
size: 1
shape: ()
ndim: 0
dtype: float64
itemsize: 8
nbytes: 8
memory used: 64


In [22]:
o2=np.ones([2,3])
print(o2)
print("size:",o2.size)
print("shape:",o2.shape)
print("ndim:",o2.ndim)
print("dtype:",o2.dtype)
print("itemsize:",o2.itemsize)
print("nbytes:",o2.nbytes)
print("memory used:",o2.itemsize*o2.nbytes)

[[1. 1. 1.]
 [1. 1. 1.]]
size: 6
shape: (2, 3)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 48
memory used: 384


In [23]:
e=np.empty()
print(e)

TypeError: empty() missing required argument 'shape' (pos 0)

In [24]:
e1=np.empty([])
print(e1)
print("size:",e1.size)
print("shape:",e1.shape)
print("ndim:",e1.ndim)
print("dtype:",e1.dtype)
print("itemsize:",e1.itemsize)
print("nbytes:",e1.nbytes)
print("memory used:",e1.itemsize*e1.nbytes)

1.0
size: 1
shape: ()
ndim: 0
dtype: float64
itemsize: 8
nbytes: 8
memory used: 64


In [28]:
e2=np.empty([2,3])
print(e2)
print("size:",e2.size)
print("shape:",e2.shape)
print("ndim:",e2.ndim)
print("dtype:",e2.dtype)
print("itemsize:",e2.itemsize)
print("nbytes:",e2.nbytes)
print("memory used:",e2.itemsize*e2.nbytes)

[[1. 1. 1.]
 [1. 1. 1.]]
size: 6
shape: (2, 3)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 48
memory used: 384


In [29]:
l=np.linspace()
print(l)

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [30]:
l1=np.linspace(1)
print(l1)

TypeError: linspace() missing 1 required positional argument: 'stop'

In [33]:
l2=np.linspace(2,3)
print(l2)
print("size:",l2.size)
print("shape:",l2.shape)
print("ndim:",l2.ndim)
print("dtype:",l2.dtype)
print("itemsize:",l2.itemsize)
print("nbytes:",l2.nbytes)
print("memory used:",l2.itemsize*l2.nbytes)

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
size: 50
shape: (50,)
ndim: 1
dtype: float64
itemsize: 8
nbytes: 400
memory used: 3200


In [35]:
import numpy as np
e1=np.eye()
print(e1)

TypeError: eye() missing 1 required positional argument: 'N'

In [36]:
i=np.identity()
print(i)

TypeError: identity() missing 1 required positional argument: 'n'

In [38]:
e2=np.eye(2)
print(e2)
print("size:",e2.size)
print("shape:",e2.shape)
print("ndim:",e2.ndim)
print("dtype:",e2.dtype)
print("itemsize:",e2.itemsize)
print("nbytes:",e2.nbytes)
print("*===*"*10)
print("Identity:")
i2=np.identity(2)
print(i2)
print("size:",i2.size)
print("shape:",i2.shape)
print("ndim:",i2.ndim)
print("dtype:",i2.dtype)
print("itemsize:",i2.itemsize)
print("nbytes:",i2.nbytes)
print("memory used:",i2.itemsize*i2.nbytes)

[[1. 0.]
 [0. 1.]]
size: 4
shape: (2, 2)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 32
*===**===**===**===**===**===**===**===**===**===*
Identity:
[[1. 0.]
 [0. 1.]]
size: 4
shape: (2, 2)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 32
memory used: 256


In [42]:
e3=np.eye(2,3)
print(e3)
print("size:",e3.size)
print("shape:",e3.shape)
print("ndim:",e3.ndim)
print("dtype:",e3.dtype)
print("itemsize:",e3.itemsize)
print("nbytes:",e3.nbytes)
print("memory used:",e3.itemsize*e3.nbytes)
print("*==*"*10)
print("Identity:")
i3=np.identity(2,3)
print(i3)

[[1. 0. 0.]
 [0. 1. 0.]]
size: 6
shape: (2, 3)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 48
memory used: 384
*==**==**==**==**==**==**==**==**==**==*
Identity:


TypeError: 'tuple' object cannot be interpreted as an integer

In [43]:
d=np.diag()
print(d)

TypeError: diag() missing 1 required positional argument: 'v'

In [44]:
t=np.tri()
print(t)

TypeError: tri() missing 1 required positional argument: 'N'

In [51]:
print("Diagonal:")
d1=np.diag([1,2,3])
print(d1)
print("size:",d1.size)
print("shape:",d1.shape)
print("ndim:",d1.ndim)
print("dtype:",d1.dtype)
print("itemsize:",d1.itemsize)
print("nbytes:",d1.nbytes)
print("memory used:",d1.itemsize*d1.nbytes)
print("*===*"*10)
print("Lower Triangle:")
t1=np.tri(4,3)
print(t1)
print("size:",t1.size)
print("shape:",t1.shape)
print("ndim:",t1.ndim)
print("dtype:",t1.dtype)
print("itemsize:",t1.itemsize)
print("nbytes:",t1.nbytes)
print("memory used",t1.itemsize*t1.nbytes)

Diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]
size: 9
shape: (3, 3)
ndim: 2
dtype: int64
itemsize: 8
nbytes: 72
memory used: 576
*===**===**===**===**===**===**===**===**===**===*
Lower Triangle:
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
size: 12
shape: (4, 3)
ndim: 2
dtype: float64
itemsize: 8
nbytes: 96
memory used 768


In [56]:
import numpy as np
a=np.array([2,3,4])
a1=np.array([[5,6,7],[8,9,0]])
#Mathematical operation
add=a+a1
print("add:",add)
dif=a1-a
print("\n diff:\n",dif)
product=a*a1
print("\n product:\n",product)
div=a1/a
print("\n div:\n",div)
modulas=a1%a
print("\n modulas:\n",modulas)

add: [[ 7  9 11]
 [10 12  4]]

 diff:
 [[ 3  3  3]
 [ 6  6 -4]]

 product:
 [[10 18 28]
 [16 27  0]]

 div:
 [[2.5  2.   1.75]
 [4.   3.   0.  ]]

 modulas:
 [[1 0 3]
 [0 0 0]]


In [57]:
# aggregation function
import numpy as np
a1=np.array([2,3,4])
print("\n sum:\n",a1.sum())
print("\n mean:\n",a1.mean())
print("\n min:\n",a1.min())
print("\n max:\n",a1.max())
print("\n std:\n",a1.std())
print("\n var:\n",a1.var())
print("\n median:\n",np.median(a1))
print("\n percentile:\n",np.percentile(a1,25))


 sum:
 9

 mean:
 3.0

 min:
 2

 max:
 4

 std:
 0.816496580927726

 var:
 0.6666666666666666

 median:
 3.0

 percentile:
 2.5


In [60]:
print("square:\n",np.square(a1))
print("sqrt:\n",np.sqrt(a1))
print("log:\n",np.log(a1))
print("sin:\n",np.sin(a1))
print("cos:\n",np.cos(a1))

square:
 [ 4  9 16]
sqrt:
 [1.41421356 1.73205081 2.        ]
log:
 [0.69314718 1.09861229 1.38629436]
sin:
 [ 0.90929743  0.14112001 -0.7568025 ]
cos:
 [-0.41614684 -0.9899925  -0.65364362]


In [66]:
a3=np.array([[11,12,13],[14,15,16]])
a2=np.array([[10,20,30],[40,50,60]])
print("sum:\n",a2.sum())
print("max:\n",a2.max())
print("min:\n",a2.min())
print("mean:\n",a2.mean())
print("std:\n",a2.std())
print("var:\n",a2.var())
print(" median:\n",np.median(a2))
print("percentile:\n",np.percentile(a2,75))
print("square:\n",np.square(a2))
print("sqrt:\n",np.sqrt(a2))
print("log:\n",np.log(a2))
print("sin:\n",np.sin(a2))
print("cos:\n",np.cos(a2))

sum:
 210
max:
 60
min:
 10
mean:
 35.0
std:
 17.07825127659933
var:
 291.6666666666667
 median:
 35.0
percentile:
 47.5
square:
 [[ 100  400  900]
 [1600 2500 3600]]
sqrt:
 [[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
log:
 [[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]
sin:
 [[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]
cos:
 [[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [81]:
import numpy as np
a1=np.array([[10,20,3],[11,12,4]])
a2=np.array([[5,10,1],[15,20,2],[25,30,3]])
print("dot product:\n",np.dot(a1,a2))
t=np.transpose(a1)
print("Before transpose:\n",a1)
print("After transpose:\n",t)

dot product:
 [[425 590  59]
 [335 470  47]]
Before transpose:
 [[10 20  3]
 [11 12  4]]
After transpose:
 [[10 11]
 [20 12]
 [ 3  4]]


In [82]:
inv=np.linalg.inv(a2)
print("Before inv:\n",a2)
print("After inv:\n",inv)

Before inv:
 [[ 5 10  1]
 [15 20  2]
 [25 30  3]]
After inv:
 [[-1.80000000e-01 -3.40000000e-01  1.80000000e-01]
 [-1.00079992e+15  2.00159983e+15 -1.00079992e+15]
 [ 1.00079992e+16 -2.00159983e+16  1.00079992e+16]]


In [84]:
det=np.linalg.det(a2)
print("Before determinant:\n",a2)
print("After determinant:\n",det)

Before determinant:
 [[ 5 10  1]
 [15 20  2]
 [25 30  3]]
After determinant:
 -4.996003610813198e-15


In [85]:
eigenvalue ,eigenvactor=np.linalg.eig(a2)
print("Eigen value:\n",eigenvalue)
print("Eigen vactor:\n",eigenvactor)

Eigen value:
 [ 3.000000e+01 -2.000000e+00  1.307875e-16]
Eigen vactor:
 [[-2.43934688e-01 -4.36435780e-01 -1.05859556e-17]
 [-5.28525158e-01  2.18217890e-01 -9.95037190e-02]
 [-8.13115628e-01  8.72871561e-01  9.95037190e-01]]


In [88]:
import numpy as np
a=np.random.rand(1,2)
print(a)

[[0.75832898 0.55344336]]


In [89]:
a1=np.random.randn()
print(a1)

0.0014342705810568757


In [92]:
a3=np.random.randint(1,10,5)
print(a3)

[8 7 5 7 3]


In [94]:
a4=np.random.choice([1,2,3,4])
print(a4)

4


In [99]:
a5=np.random.randint(5,100,20)
print(a5)
a6=np.random.choice(a5)
print(a6)

[ 7 26 12 48 57 68 92 65 79 47 92 90 85 97 34 39 59 46 36 14]
39


In [100]:
a7=np.random.randint(10,20,10)
print(a7)

[15 19 19 14 18 14 17 18 16 16]


In [104]:
a8=np.sort(a7)
print(a8)
print(a8.shape)

[14 14 15 16 16 17 18 18 19 19]
(10,)


In [106]:
print(a7.reshape(1,10))

[[14 14 15 16 16 17 18 18 19 19]]


In [107]:
print(a7.flatten())

[14 14 15 16 16 17 18 18 19 19]
