## Lec-01

In [2]:
print("Talib Ansari")

Talib Ansari


- **Type Casting**


In [3]:
int(1)

1

In [35]:
print(type(int()))

<class 'int'>


In [36]:
print(id(int()))

140717207958408


In [4]:
int(5.6)

5

In [5]:
int(9+5j) # complex number can not converted to the int

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [6]:
int('a') # string also can not be converted to the int

ValueError: invalid literal for int() with base 10: 'a'

In [8]:
int('a',16) # can be converted only when there is a single char with base 16

10

In [9]:
int('ansari',16) # word can not be converted to the int with base 16

ValueError: invalid literal for int() with base 16: 'ansari'

In [10]:
int('ansari',36)  # word can be converted in int with only base 36

644613246

In [11]:
int('Pyhton is programming language',36) # sentence or the group of words can not be conveted in in

ValueError: invalid literal for int() with base 36: 'Pyhton is programming language'

In [12]:
print(int(True))

1


In [13]:
print(int(False))

0


In [14]:
print(int())

0


In [16]:
print(int(_))

644613246


In [25]:
print(int('*',128)) # special char can not be converted to the integer type

ValueError: int() base must be >= 2 and <= 36, or 0

 ------------------------------------------------------------------

In [26]:
print("I am an Engineer")

I am an Engineer


In [27]:
print(str(5))

5


In [28]:
print(str(859.48))

859.48


In [29]:
print(str(True))

True


In [30]:
print(str(False))

False


In [31]:
print(str(9+5j))

(9+5j)


In [32]:
print(str())

In [34]:
print(str(_))

644613246


In [37]:
print(type(str()))
print(id(str()))

<class 'str'>
140717207979712


 --------------------------------------------------------------------------------------------------------

In [39]:
print(float())

0.0


In [42]:
print(float(_))

644613246.0


In [43]:
print(float(10))

10.0


In [48]:
print(float('10'))

10.0


In [46]:
print(float('a')) # If String is char then it can't be converted to the float at any view

TypeError: float expected at most 1 argument, got 2

In [47]:
print(float(6+5j)) # Complex number can't be converted to the float

TypeError: float() argument must be a string or a real number, not 'complex'

In [49]:
print(float(True))

1.0


In [50]:
print(float(False))

0.0


 ----------------------------------------------------------------------------------------------------------------------------------------------

In [69]:
print(complex())

0j


In [76]:
print(complex(_))

(644613246+0j)


In [51]:
print(complex(1))

(1+0j)


In [52]:
print(complex(0))

0j


In [53]:
print(complex(0,0))

0j


In [54]:
print(complex(int(2)))

(2+0j)


In [58]:
print(complex(float(8.7)))

(8.7+0j)


In [57]:
print(complex(5.5,9.2))

(5.5+9.2j)


In [59]:
print(complex(True))

(1+0j)


In [60]:
print(complex(False))

0j


In [62]:
print("Complex with integer:",complex(1,1))
print("Complex with bool func:",complex(True,True))
print("="*50)
print("Complex with integer:",complex(False,False))
print("Complex with bool func:",complex(0,0))
print("="*50)
print("Complex with integer:",complex(True,False))
print("Complex with bool func:",complex(1,0))

Complex with integer: (1+1j)
Complex with bool func: (1+1j)
Complex with integer: 0j
Complex with bool func: 0j
Complex with integer: (1+0j)
Complex with bool func: (1+0j)


In [64]:
print(complex('1'))

(1+0j)


In [63]:
print(complex('1',2)) # it won't take second if first arg is string

TypeError: complex() can't take second arg if first is a string

In [65]:
print(complex(2,'2')) # Second arg must be integer or float it can't be  string

TypeError: complex() second arg can't be a string

In [66]:
print(complex(1,2,3)) # it takes only two arg:1.for a,2.for bj (a+bj)

TypeError: complex() takes at most 2 arguments (3 given)

 ------------------------------------------------------------------------------------------------------------------------------------------------------

In [70]:
print(bool())

False


In [71]:
print(bool(_))

True


In [72]:
print(bool(__)) # __ value is 10, ___ value is 5 ,____ value is not defined

True


In [80]:
print(bool(float()))

False


In [81]:
print(bool(int(5)))

True


In [82]:
print(bool(3+2j))

True


In [84]:
print(bool(1.1))

True


In [85]:
print(bool('str'))

True


In [86]:
print(bool('1'))

True


--------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------

## Lec -02

In [ ]:
'''
Data Type (Primitive Data Type) :
  Data Type always takes one value at a time or while assigning a variable it would take one value.
  such as: a=5
           b=10   
        Both variables a & b have one-one value which of integer type   
  1.int
  2.float
  3.str
  4.bool
  5.complex


Non-Primitive Data Types:
     Non-Primitive Data Types also called as the Data Strutures because in Primitive Data Type we have only one value at a variabl but here
     we structure multiple values to at one variable in structured manner.
     such as:a=5,6,7,8
    1.Built in Data Type:
         a.List
         b.Tuple
         c.Set
         d.Dict

    2.User Defined Data Type:
         a.Stack
         b.queue
         c.Tree
         d.Graph

DataFrame : DataFrame is the set of the multiple data structures
   such as : Grid or Matrix 
'''

- **List**

In [88]:
# List Creation
l=list()
print(type(l))

<class 'list'>


In [89]:
l1=[]
print(type(l1))

<class 'list'>


In [90]:
l3=[1,2,3,4,5]
print(l3)

[1, 2, 3, 4, 5]


In [92]:
l4=l3
print(l4)

[1, 2, 3, 4, 5]


In [93]:
print(l3 is l4) # it checks the address

True


In [94]:
print(l3==l4) # it checks the value inside the list

True


In [95]:
print(id(l3))

2386355188608


In [96]:
print(id(l4))

2386355188608


In [97]:
list_1=[5,10,15,20]
list_2=[5,10,15,20]
print("List_1:",list_1)
print("List_2:",list_2)

List_1: [5, 10, 15, 20]
List_2: [5, 10, 15, 20]


In [98]:
print(list_1 is list_2)

False


In [99]:
print(list_1==list_2)

True


In [100]:
print(id(list_1)==id(list_2))

False


In [104]:

del l3 # to delete the entire list
del l4

In [106]:
l3=[2,4,8,12]
l4=l3.copy()
print("L3:",l3)
print("L4:",l4)

L3: [2, 4, 8, 12]
L4: [2, 4, 8, 12]


In [107]:
print(l3 is l4)

False


In [108]:
print("l3 id:",id(l3))
print("l4 id:",id(l4))

l3 id: 2386355809024
l4 id: 2386355804544


In [109]:
print(l3==l4)

True


In [110]:
# Slicing
# 1. Forward slicing
# [2, 4, 8, 12]
#  0  1  2  3
print(l3)

[2, 4, 8, 12]


In [111]:
l3[:]

[2, 4, 8, 12]

In [113]:
l3[0:]

[2, 4, 8, 12]

In [114]:
l3[0:2]

[2, 4]

In [115]:
l3[2:3]

[8]

In [117]:
l3[0:4:1]

[2, 4, 8, 12]

In [118]:
l3[0:4:2]

[2, 8]

In [121]:
l3[1:4:3]

[4]

In [123]:
l3[1]

4

In [125]:
l3[2]

8

In [126]:
# 2.Backward Slicing
# [2, 4, 8, 12]
# -4 -3 -2 -1
l3

[2, 4, 8, 12]

In [127]:
l3[-1]

12

In [128]:
l3[-3]

4

In [129]:
l3[:]

[2, 4, 8, 12]

In [130]:
l3[:-1]

[2, 4, 8]

In [131]:
l3[-1:]

[12]

In [140]:
l3[-4:-1:2]

[2, 8]

In [141]:
l3.pop()

12

In [142]:
l3.pop(2)

8

In [143]:
l3.remove(4)

In [145]:
l3.pop()

2

In [146]:
del l3

In [149]:
l1=[1,2,3,4,'a','b','c']
print(l1)

[1, 2, 3, 4, 'a', 'b', 'c']


In [150]:
print('a' in l1) # Membership Operrator 'in'

True


In [151]:
print(1 in l1)

True


In [154]:
# List Concatenation  {not supported with :+,-,/,//,%}
l2=l1+10

TypeError: can only concatenate list (not "int") to list

In [157]:
l2=l1*2
l2

[1, 2, 3, 4, 'a', 'b', 'c', 1, 2, 3, 4, 'a', 'b', 'c']

In [164]:
for i in enumerate(l1):
    print(i,end=',')

(0, 1),(1, 2),(2, 3),(3, 4),(4, 'a'),(5, 'b'),(6, 'c'),

In [168]:
# List Element Reversing without using inbuilt functions
n=len(l1)-1
while n>-1:
    print(l1[n])
    n-=1

c
b
a
4
3
2
1


In [170]:
n=len(l1)-1
a=[]
while n>-1:
    a.append(l1[n])
    n-=1
print(a)

['c', 'b', 'a', 4, 3, 2, 1]


In [202]:
# Reversing with inbuilt functon
l1.reverse()
l1

['c', 'b', 'a', 4, 3, 2, 1]

In [203]:
l2=[2,8,4,3,7,9,0]
l2.reverse()
l2

[0, 9, 7, 3, 4, 8, 2]

In [204]:
l2.sort()
l2

[0, 2, 3, 4, 7, 8, 9]

In [206]:
l2.extend(l1)
l2

[0, 2, 3, 4, 7, 8, 9, 'c', 'b', 'a', 4, 3, 2, 1, 'c', 'b', 'a', 4, 3, 2, 1]

In [208]:
any(l1)

True

In [209]:
all(l1)

True

 - Tuple

In [211]:
# tuple creation
t1=tuple()
print(t1,type(t1))

() <class 'tuple'>


In [225]:
t2=()
print(t2,type(t2))

() <class 'tuple'>


In [213]:
del t1
del t2

In [214]:
t1=(1,2,3,4,5)
t2=(1,2,3,'a','b','c')
t3=(0,1,'@','%','$')
t4=((1,2,3,4),
    ('talib','ansari'),
    ('@','4','*'))
print("Normal Tuple:",t1)
print("Mixed tuple with Char:",t2)
print("Mixed with Special Char:",t3)
print("Nested Tuple:",t4)

Normal Tuple: (1, 2, 3, 4, 5)
Mixed tuple with Char: (1, 2, 3, 'a', 'b', 'c')
Mixed with Special Char: (0, 1, '@', '%', '$')
Nested Tuple: ((1, 2, 3, 4), ('talib', 'ansari'), ('@', '4', '*'))


In [215]:
t5=t1+10

TypeError: can only concatenate tuple (not "int") to tuple

In [217]:
t5=t1*2
t5

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)

In [218]:
t1[1]

2

In [219]:
t1[2]=5

TypeError: 'tuple' object does not support item assignment

In [221]:
for i in enumerate(t1):
    print(i,end=",")

(0, 1),(1, 2),(2, 3),(3, 4),(4, 5),

In [227]:
t1.count(5)

1

In [228]:
t1.index(2)

1

# Lec -05

 - Set

In [229]:
# Set Creation 
s={} # by default dict
print(type(s))

<class 'dict'>


In [230]:
s1=set()
print(type(s1))

<class 'set'>


In [231]:
s2={1,2,3,4}
print(s2)

{1, 2, 3, 4}


In [232]:
s3={1,2,3,4,'a','b','c'}
print(s3)

{'b', 1, 2, 3, 4, 'a', 'c'}


In [233]:
s4={1,1,1,1,1,'a','a','a'} # Duplicates removed 
print(s4)

{1, 'a'}


In [234]:
s5={{1,2,3},{4,5,6}} # Nested Set is not allowed
print(s5)

TypeError: unhashable type: 'set'

In [236]:
s6={1,2,3,(4,5)}
print(s6)

{3, 1, (4, 5), 2}


In [237]:
s7={2,3,4,[5,6],7}

TypeError: unhashable type: 'list'

In [239]:
s6[:]

TypeError: 'set' object is not subscriptable

In [242]:
s6.add(9)
s6

{(4, 5), 1, 2, 3, 9}

In [243]:
s6.pop()

1

In [244]:
s6.pop()

2

In [245]:
s6.remove(9)

In [246]:
s6

{(4, 5), 3}

In [247]:
s6.discard(6) # it smoothly removes te element if element is not there it does not produce any error

 - set operations

In [248]:
set_1={1,2,3,4,5,6,7}
set_2={5,6,4}
# Union
un=set_1 | set_2
un2=set_1.union(set_2)
print("Union1:",un)
print("Union2:",un2)

Union1: {1, 2, 3, 4, 5, 6, 7}
Union2: {1, 2, 3, 4, 5, 6, 7}


In [249]:
# Intersection (Common)
in1=set_1 & set_2
in2=set_1.intersection(set_2)
print("Intersection1:",in1)
print("Intersection2:",in2)

Intersection1: {4, 5, 6}
Intersection2: {4, 5, 6}


In [250]:
# Symmetric difference
diff=set_1.difference(set_2)
diff2=set_1.symmetric_difference(set_2)
print("Diff:",diff)
print("Diff2:",diff2)

Diff: {1, 2, 3, 7}
Diff2: {1, 2, 3, 7}


In [254]:
# Disjoint
dis1=set_1^set_2

print("Dis1:",dis1)


Dis1: {1, 2, 3, 7}


In [256]:
# Subset
print(set_2.issubset(set_1))

True


In [257]:
# Superset
print(set_1.issuperset(set_2))

True


In [9]:
# Exclusive or Ordinary progrmas of Set
# 1.
# set_1={1,2,3,4,['a','b']}
# print("Set_1:",set_1)
# print("---"*20)

set_2={'a','b','c',(2,3)}
print("Set_2:",set_2)
print("---"*20)

# set_3={1,'a','c',{1,2}}
# print("Set_3:",set_3)

Set_2: {(2, 3), 'a', 'c', 'b'}
------------------------------------------------------------


In [3]:
try:
    set_1={1,2,3,4,['a','b']}
    print("Set_1:",set_1)
except TypeError as t:
    print(f"Set Can not be written in nested form")

Set Can not be written in nested form


In [8]:
try:
    set_3={1,'a','c',{1,2}}
    print("Set_3:",set_3)
except TypeError as t:
    print(f"Error:{t}")

Error:unhashable type: 'set'


In [10]:
set_4={1,1,1,1,1,0,0,0,0}
print("Set 4:",set_4)
print("---"*30)

set_5={1,1,1,1,1,1,True}
print("Set 5:",set_5)
print("---"*30)


set_6={True,1,1,1,1,1}
print("Set 6:",set_6)
print("---"*30)


set_7={1,True,True,True,True,True,True}
print("Set 7:",set_7)
print("---"*30)


set_8={0,False ,False,0,0,False ,0,0}
print("Set 8:",set_8)

Set 4: {0, 1}
------------------------------------------------------------------------------------------
Set 5: {1}
------------------------------------------------------------------------------------------
Set 6: {True}
------------------------------------------------------------------------------------------
Set 7: {1}
------------------------------------------------------------------------------------------
Set 8: {0}


 - **Dict**

In [11]:
dict_1={'a':1,'b':2,'c':3,'d':4}
print(dict_1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [12]:
dict_1.keys()

dict_keys(['a', 'b', 'c', 'd'])

In [14]:
dict_1.values()

dict_values([1, 2, 3, 4])

In [15]:
len(dict_1)

4

In [16]:
dict_1['e']=5
dict_1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [17]:
dict_1['a']=10
dict_1

{'a': 10, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [24]:
dict_1.update(b=20)
dict_1

{'a': 10, 'b': 20, 'c': 3, 'd': 4, 'e': 5}

In [25]:
# input
n=int(input("Enter number here:"))
dict_2={}
for i in range(n+1):
    key=input("Enter key here:")
    value=input("Enter Value here:")
    dict_2[key]=value
print(dict_2)

Enter number here: 5
Enter key here: Name
Enter Value here: Talib Ansari
Enter key here: Occupation
Enter Value here: Student
Enter key here: Age
Enter Value here: 21
Enter key here: College
Enter Value here: RITS
Enter key here: Degree
Enter Value here: Computer Science Engineering
Enter key here: College Add
Enter Value here: Bhopal,Ratibad


{'Name': 'Talib Ansari', 'Occupation': 'Student', 'Age': '21', 'College': 'RITS', 'Degree': 'Computer Science Engineering', 'College Add': 'Bhopal,Ratibad'}


# Lec -07

In [27]:
a=10
b=5
add=a+b
sub=a-b
pro=a*b
float_div=a/b
true_div=a//b
modulas=a%b # it gives remainder
print("Add:",add)
print("Sub:",sub)
print("Prod:",pro)
print("Float Division:",float_div)
print("True Division:",true_div)
print("Modulas:",modulas)

Add: 15
Sub: 5
Prod: 50
Float Division: 2.0
True Division: 2
Modulas: 0


In [28]:
# some try:
c=a+b- # Syntax Errors Are Compile Time Errors 

SyntaxError: invalid syntax (2401862510.py, line 2)

In [29]:
c=a%%b

SyntaxError: invalid syntax (200586605.py, line 1)

In [30]:
print("Nit")

Nit


In [37]:
d=4*"Nit"
print(d)

NitNitNitNit


In [38]:
e=4+"Nit"
print(e)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [43]:

print('Hey i am  a "python developer"! ')

Hey i am  a "python developer"! 


In [49]:
# SyntaxError: unterminated
print("Hello \"Coders" ")

SyntaxError: unterminated string literal (detected at line 2) (3568772894.py, line 2)

In [53]:
print("Nit ','Technology")

Nit ','Technology


In [56]:
print('nit'  'nit')

nitnit


In [63]:
x=10
y=20
z=x+y
print(z)

30


In [68]:
_+y # 20

TypeError: can only concatenate str (not "int") to str

In [69]:
s='Talib'
print(s)

Talib


In [71]:
t='A'+s[0]
t

'AT'

In [72]:
y='An'+s[0:2]
y

'AnTa'

In [73]:
help()

Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".



help>  topics



Here is a list of available topics.  Enter any topic name to get more help.

ASSERTION                 EXCEPTIONS                PACKAGES
ASSIGNMENT                EXECUTION                 POWER
ASSIGNMENTEXPRESSIONS     EXPRESSIONS               PRECEDENCE
ATTRIBUTEMETHODS          FLOAT                     PRIVATENAMES
ATTRIBUTES                FORMATTING                RETURNING
AUGMENTEDASSIGNMENT       FRAMEOBJECTS              SCOPING
BASICMETHODS              FRAMES                    SEQUENCEMETHODS
BINARY                    FUNCTIONS                 SEQUENCES
BITWISE                   IDENTIFIERS               SHIFTING
BOOLEAN                   IMPORTING                 SLICINGS
CALLABLEMETHODS           INTEGER                   SPECIALATTRIBUTES
CALLS                     LISTLITERALS              SPECIALIDENTIFIERS
CLASSES                   LISTS                     SPECIALMETHODS
CODEOBJECTS               LITERALS                  STRINGMETHODS
COMPARISON                L

help>  DICTIONARIES              


Mapping Types — "dict"
**********************

A *mapping* object maps *hashable* values to arbitrary objects.
Mappings are mutable objects.  There is currently only one standard
mapping type, the *dictionary*.  (For other containers see the built-
in "list", "set", and "tuple" classes, and the "collections" module.)

A dictionary’s keys are *almost* arbitrary values.  Values that are
not *hashable*, that is, values containing lists, dictionaries or
other mutable types (that are compared by value rather than by object
identity) may not be used as keys. Values that compare equal (such as
"1", "1.0", and "True") can be used interchangeably to index the same
dictionary entry.

class dict(**kwargs)
class dict(mapping, **kwargs)
class dict(iterable, **kwargs)

   Return a new dictionary initialized from an optional positional
   argument and a possibly empty set of keyword arguments.

   Dictionaries can be created by several means:

   * Use a comma-separated list of "key: value" pairs wit

help>  q



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


- **Operators**

In [ ]:
# 1.Arithmatic Operation(+,-,*,/,//,%)
# Done above


In [88]:
# 2.Assignment Operators(+=,-=,*=,/=)


In [84]:
a=5
a+=10
a

15

In [85]:
a-=8
a

7

In [87]:
a*=5
a

175

In [89]:
a/=5
a

35.0

In [91]:
b=2
c=5
d=c**b
d

25

In [ ]:
# 3.Unary Operator(m=-n)

In [92]:
# 4.Relational Operator(<,>,<=,>=,|,&,==,!=)
val1=10
val2=14

if val1>val2:
    print("Val1 is greater")
else:
    print("Val2 is greater")

Val2 is greater


In [95]:
a=-3
b=1
c=4
if a>b:
    if c<a:
        print("A is Greater")
    else:
        print("C is Greater")
else:
    if b>c:
        print("B is greater ")
    else:
        print("C is greater")

C is greater


In [101]:
# Check Entered Char is variable
char=input("Enter Char here:")
if char=='a' or char=='A' or char=='e' or char=='E' or char=='i' or char=='I' or char=='o' or char=='O' or char=='u' or char=='U':
    print(f'{char} is a char')
else:
    print(f'{char} is not a char')

Enter Char here: t


t is not a char


# Lec -08

In [103]:
import math as m
print("Square root:",m.sqrt(4))
print("Power :",m.pow(2,4))
print("PI Value:",m.pi)
print("Exponential Value:",m.e)
print("Ceiling Value:",m.ceil(10.8))
print("Floor Value:",m.floor(10.8))

Square root: 2.0
Power : 16.0
PI Value: 3.141592653589793
Exponential Value: 2.718281828459045
Ceiling Value: 11
Floor Value: 10


In [105]:
from math import*
print(sqrt(8))


2.8284271247461903


In [106]:
help()

Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".



help>  modules



Please wait a moment while I gather a list of all available modules...



C:\Users\talib\anaconda3\Lib\site-packages\nltk\twitter\__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(
C:\Users\talib\anaconda3\Lib\site-packages\pydantic\experimental\__init__.py:7: PydanticExperimentalWarning:

This module is experimental, its contents are subject to change and deprecation.

C:\Users\talib\anaconda3\Lib\pkgutil.py:78: UserWarning:

The superqt.qtcompat module is deprecated as of v0.3.0. Please import from `qtpy` instead.

W1223 19:08:52.292000 46932 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\talib\anaconda3\Lib\pkgutil.py:78: DeprecationWarning:

`torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead

C:\Users\talib\anaconda3\Lib\pkgutil.py:78: DeprecationWarning:

`torch.distributed._sharded_tensor` will be dep

3204bda914b7f2c6f497__mypyc codecs              mimetypes           sklearn
IPython             codeop              mistune             sklearn_compat
OpenSSL             collections         mkl                 slugify
PIL                 colorama            mkl_fft             smmap
PyQt5               colorcet            mkl_random          smtplib
__future__          colorsys            mmap                sniffio
__hello__           comm                mmapfile            snowballstemmer
__phello__          commctrl            mmsystem            socket
_abc                compileall          modulefinder        socketserver
_aix_support        concurrent          more_itertools      socks
_android_support    conda               mouseinfo           sockshandler
_apple_support      conda_anaconda_telemetry mpmath              sortedcontainers
_argon2_cffi_bindings conda_anaconda_tos  msgpack             soupsieve
_ast                conda_build         msvcrt              sphinx
_as

help>  math


Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

help>  q



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


# Lec -09

In [107]:
import numpy as np
np.__version__

'2.1.3'

In [109]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [112]:
z2=np.zeros(5,dtype=int)
z2

array([0, 0, 0, 0, 0])

In [115]:
z3=np.zeros((3,3))
z3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
z4=np.zeros((2,3,4),dtype=int)
z4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [119]:
o1=np.ones(2)
o1

array([1., 1.])

In [121]:
o2=np.ones(4,dtype=int)
o2

array([1, 1, 1, 1])

In [122]:
o3=np.ones((2,2),dtype=int)
o3

array([[1, 1],
       [1, 1]])

In [123]:
o4=np.ones((2,2,2),dtype=int)
o4

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [124]:
np.random.rand(2)

array([0.4289722 , 0.66582019])

In [125]:
np.random.rand(4)

array([0.46172273, 0.70708022, 0.17199011, 0.59600448])

In [126]:
np.random.rand(2,3)

array([[0.74814924, 0.59889304, 0.82117787],
       [0.4482244 , 0.95882093, 0.15073148]])

In [127]:
np.random.rand(2,3,4)

array([[[0.0358868 , 0.71069933, 0.92972538, 0.55446732],
        [0.02830655, 0.61731613, 0.13679075, 0.18445558],
        [0.45566633, 0.07649892, 0.45181344, 0.92728963]],

       [[0.46252239, 0.66060405, 0.27646251, 0.89352981],
        [0.9805074 , 0.08720315, 0.71753637, 0.77295987],
        [0.26137143, 0.62094584, 0.02182185, 0.04742509]]])

In [128]:
np.random.rand(2,3,4,5)

array([[[[0.49685678, 0.84803767, 0.21714601, 0.629531  , 0.17425207],
         [0.82167707, 0.08433528, 0.02246487, 0.75876805, 0.41108249],
         [0.45343321, 0.64429329, 0.10043033, 0.69002823, 0.88560077],
         [0.41238476, 0.88750057, 0.18071467, 0.5022707 , 0.14448143]],

        [[0.04571546, 0.18162647, 0.34303957, 0.40476789, 0.18188305],
         [0.00252324, 0.06273256, 0.08274684, 0.2671073 , 0.26980246],
         [0.47489174, 0.38406585, 0.89060457, 0.2624626 , 0.14320193],
         [0.17786892, 0.7792445 , 0.47334154, 0.08246288, 0.12602624]],

        [[0.39513187, 0.33206414, 0.3432868 , 0.54015926, 0.37393187],
         [0.16700588, 0.26082026, 0.56029506, 0.99224639, 0.38400101],
         [0.42819681, 0.10157413, 0.86892275, 0.21727562, 0.31413595],
         [0.4532649 , 0.57996827, 0.18479826, 0.92138219, 0.72021691]]],


       [[[0.37752508, 0.9992972 , 0.30979027, 0.91356354, 0.76090966],
         [0.30605753, 0.26731321, 0.46852421, 0.88226039, 0.07171347]

In [130]:
np.random.randint(1)

0

In [131]:
np.random.randint(2)

1

In [135]:
np.random.randint(10)

5

In [136]:
np.random.randint(2,3)

2

In [138]:
np.random.randint(3,4,3)

array([3, 3, 3], dtype=int32)

In [139]:
np.random.randint(2,10,4)

array([6, 8, 9, 2], dtype=int32)

In [140]:
np.random.randint(4,10,(2,2))

array([[6, 9],
       [4, 6]], dtype=int32)